### ISSUE TITLE
Introducing an intermediate wrapper to represent the MEx data.

### ISSUE THREAD

**Issue by amdomanska** [robert-koch-institut/mex-invenio#10]
## Deliverables
- [x] MEx data is represented with a semantic wrapper for crosswalk implementation.

## Overview
Provide a semantic wrapper around the MEx file for use during crosswalk implementation (and later for landing page rendering)

## Tasks
- [x] Define core concepts and create a glossary.
- [x] Standardise the metadata structure and develop documentation.
