### ISSUE TITLE
Developing and implementing the internal Invenio model and MEx mapping.

### ISSUE THREAD

**Issue by amdomanska** [robert-koch-institut/mex-invenio#11]
## Deliverables

- [x] Internal metadata model for Invenio is defined and meets project requirements.
- [x] MEx data is mapped to the internal Invenio model for projects, resources, and publications.
- [x] Invenio back-end supports the new internal model.
- [x] MEx data is ingested into Invenio through the developed crosswalks.
- [ ] MEx data pipeline for Invenio API is implemented.

## Tasks
- [x] Define an internal metadata model which meets the requirements
- [x] Define the mapping from MEx to the internal metadata model for each searchable entity type (projects, resources, publications)
- [x] Implement support for the model in the Invenio back-end
- [x] Implement crosswalks from MEx to the internal model on ingest.
- [ ] Implement MEx data pipeline for Invenio API

This will be implemented by using the supplied test data to produce Invenio objects

Each of the above elements will need to take into account the possibility that a given field in MEx is available in multiple languages, and those languages will need to be accommodated in Invenio’s internal model.

Developers Issues:
#9 Implement Schema-to-CustomFields script  
#2 Decide on metadata schema implementation  
#17 Implement the Mex/Invenio crosswalk
