### ISSUE TITLE
Exposing custom data via OAI-PMH

### ISSUE THREAD

**Issue by amdomanska** [robert-koch-institut/mex-invenio#13]
PR: https://github.com/robert-koch-institut/mex-invenio/pull/30

## Deliverables

- [ ] Invenio internal metadata model is accessible via OAI-PMH including support for multi-lingual data.

## Tasks

- [ ] Map the new internal Invenio metadata model to oai_dc for OAI-PMH support
- [ ] Use the `@lang` attributes of the oai_dc elements to support multi-lingual data

**Comment by fdiehr** [comment]
I took a look at the OAI endpoint [here](https://mex-invenio.azure.cottagelabs.com/oai2d?verb=ListRecords&metadataPrefix=oai_dc), and I can't identify the changes that were made in [PR#30](https://github.com/robert-koch-institut/mex-invenio/pull/30/). Especially the [mapping of the mex fields to DC](https://github.com/robert-koch-institut/mex-invenio/pull/30/files#diff-2dd1a99b11bb6b49db9d54e124e282c145c9fc8571179dc1da3f28420ac0b184). 

Example:
`    <record>
      <header>
        <identifier>oai:mex.rki.de:p63gn-8f589</identifier>
        <datestamp>2025-03-10T15:15:50Z</datestamp>
      </header>
      <metadata>
        <oai_dc:dc xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:oai_dc="http://www.openarchives.org/OAI/2.0/oai_dc/" xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/oai_dc/ http://www.openarchives.org/OAI/2.0/oai_dc.xsd">
          <dc:creator>Robert Koch Institute</dc:creator>
          <dc:date>2025-03-10</dc:date>
          <dc:identifier>oai:mex.rki.de:p63gn-8f589</dc:identifier>
          <dc:rights>info:eu-repo/semantics/closedAccess</dc:rights>
          <dc:title>Deep him deep enough back east. Agency floor analysis sense. Rich should item second. South performance color. Probably remain trouble black box author value. Continue defense allow test. Ground interesting action art. North market main lay record take by. Enough thought magazine front analysis practice final plan. Ago pretty information baby anyone blood here better. Class job before fact decade sell raise. Offer develop analysis. Town approach mind rich agency hand. Remain at oil bed make total until. Like forget heart cut bed surface door show.</dc:title>
        </oai_dc:dc>
      </metadata>
    </record>`

This record is of entity `VaribaleGroup` and according to the [mapping file (lines 203-204)](site/mex_invenio/config/settings.py), it should have a `<dc:source>` field. We mapped `mex:containedBy` to `dc:source`. According to the invenio API, the `VariableGroup` has three identifiers in `mex:containedBy`:

![Image](https://github.com/user-attachments/assets/95688d28-e8e2-4d2a-9c2e-063a2b4a522c)

**Comment by J4bbi** [comment]
Thank you @fdiehr for your input.

Apologies if the approach we went with wasn't clearly communicated.  I have not replaced the (standard) OAI DC crosswalk but rather created a custom crosswalk `oai_mex`.

So instead of looking at:
https://mex-invenio.azure.cottagelabs.com/oai2d?verb=ListRecords&metadataPrefix=oai_dc

you provide the oai_mex prefix:
https://mex-invenio.azure.cottagelabs.com/oai2d?verb=ListRecords&metadataPrefix=oai_mex


if you want to look at a specific record, you can use:
https://mex-invenio.azure.cottagelabs.com/oai2d?verb=GetRecord&identifier=oai:mex.rki.de:g37wp-hz854&metadataPrefix=oai_mex

I can override the oai_dc metadataprefix if you would prefer.


With regards to indicating language. The Dublin Core xml guidelines suggest to use `xml:lang`. Would you like that implemented? 

See:
https://www.openarchives.org/OAI/openarchivesprotocol.html#ImpGuid
https://www.dublincore.org/specifications/dublin-core/dc-xml-guidelines/

**Comment by fdiehr** [comment]
Hi @J4bbi !

Thank you for the clarification! Sorry, I didn't get that the custom crosswalk is additional to the standard OAI crosswalk.

The oai_mex prefixed output looks good, just as expected by the PR :) 

Since the custom crosswalk oai_mex provides the "best" metadata in the sense of OAI, I do not know why we would still need the standard oai_dc. Could you name disadvantages when overriding the standard?

Regarding the `xml:lang` attribute, I think it is good practice to indicate the language, so yes, would be good to have.

**Comment by J4bbi** [comment]
Hi @fdiehr 

Thank you. I was probably being overly cautious. I didn't want to overwrite anything before there was a clear request to do so.

I will put in a PR with a few fixes soon, including this one. I am looking at how to add the language attribute.
