### ISSUE TITLE
Integration testing

### ISSUE THREAD

**Issue by amdomanska** [robert-koch-institut/mex-invenio#15]
## Deliverables

- [ ] End-to-end workflow with RKI for API integration is functional.
- [ ] Invenio API is integrated and accessible with login credentials.
- [ ] Initial integration testing between MEx management and Invenio is complete.
- [ ] Initial migration from MEx to Invenio is successfully tested.
- [ ] Disaster recovery tests from MEx to Invenio are successful.

## Description

Cottage Labs will provide the specified number of days to support the RKI with the testing process as needed, and provide responses to feedback (which includes code fixes to project code).

## Tasks

- [ ] Test and feedback on the integration between the MEx management system and the new Invenio system
- [ ] Initial migration testing - initial load of the Invenio from MEx management system
- [ ] Disaster recovery testing - tear down and recreate from scratch from MEx management system

**Comment by richard-jones** [comment]
@Steven-Eardley to add some notes on DR (and the lack of need for it) in the README for the ops documentation.  DR is just reinstall and reimport, as per normal installation.

**Comment by richard-jones** [comment]
@Steven-Eardley a question arose today regarding the versioning information.  Versioning is not handled in the source system, so exists only in Invenio - this may make a backup and DR plan required, can you comment?
