### ISSUE TITLE
Creating Helm charts for Deployment

### ISSUE THREAD

**Issue by amdomanska** [robert-koch-institut/mex-invenio#16]
## Deliverable
- [ ] Helm charts for production deployment are provided and tested on infrastructure.

## Tasks
- [ ] Provide fully implement Helm charts for production deployment
- [ ] Produce a demonstration production architecture on test infrastructure

## Additional notes

During this period it would be valuable to be able to have some time from the RKI operations team to assist in the requirements for the deployment.

**Comment by Steven-Eardley** [comment]
@cutoffthetop I am unable to create a base branch separate from `master` in https://github.com/robert-koch-institut/mex-invenio-helm due to branch rules; could you create that so that we have a destination for our customisations based on RKI infrastructure?

The Cottage Labs Azure charts are in branch https://github.com/robert-koch-institut/mex-invenio-helm/tree/feature/cl-mex-azure-deployment, along with a recent pull from upstream master.
