### ISSUE TITLE
Invenio Interface Customisation

### ISSUE THREAD

**Issue by amdomanska** [robert-koch-institut/mex-invenio#5]
- phase: 1
- estimated time (days): 6

## Resources

UX Standard:
We would like to use this standard for the public sector for UX, if possible, as it comes with accessibility:
https://gitlab.opencode.de/kern-ux/pattern-library

Look and Feel:
![Image](https://github.com/user-attachments/assets/d4b839b6-0649-4059-9ac6-3094d19bdbb9)
miroboard: https://miro.com/app/board/uXjVLfFrx2s=/
https://inspirehep.net/literature/2835154
https://inspirehep.net/literature?sort=mostrecent&size=25&page=1

Logos:
![Image](https://github.com/user-attachments/assets/04316bbb-c302-4cdb-a311-1a8b2c38a930)
![Image](https://github.com/user-attachments/assets/4395c710-f9db-438e-9f10-a1e4fe6434f6)

## Deliverables

- [ ] Invenio interface is customised with RKI branding and colours.
- [ ] Public login views and submission forms are removed.
- [ ] German is the default UI language, with English as an option.

## Tasks
- [ ] RKI branding
- [ ] RKI colour scheme
- [ ] Removal of public login views and submission forms
- [ ] Setup as German UI by default, with English available as an option

**Comment by amdomanska** [comment]
Duplicate with #6
